name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: run update
      run: sudo apt-get update -y
    - name: install dev-tools
      run: sudo apt-get -y install xfce4-dev-tools
    - uses: actions/checkout@v3
    - name: configure
      run: ./autogen.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
